name: Publish docker image

on:
  push:
    branches: ["master"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Publish the Docker image
        run: |
          docker build . --file Dockerfile --tag ghcr.io/iarahealth/nuts:latest
          docker push ghcr.io/iarahealth/nuts:latest
